### ISSUE TITLE
Hugo Now UI Theme Demo not generated on the Hugo website

### ISSUE THREAD

**Issue by onedrawingperday** [cboettig/hugo-now-ui#24]
Hello @cboettig and Happy New Year!

It seems that after you merged commit https://github.com/cboettig/hugo-now-ui/commit/0daac3f8ba596c165f78f13c68171dd87161165d you didn't commit the new resources to the theme repo and at the moment the demo of the theme is not generated on the website.

Here is the deploy log from Netlify:
```
2:01:17 PM:  ==== PROCESSING  hugo-now-ui  ======
2:01:17 PM: Building site for theme hugo-now-ui using its own exampleSite to ../themeSite/static/theme/hugo-now-ui/
2:01:17 PM: ERROR 2019/01/05 12:01:17 error: failed to transform resource: TOCSS: failed to transform "sass/now-ui-kit.scss" (text/x-scss): this feature is not available in your current Hugo version
2:01:17 PM: Error: Error building site: logged 1 error(s)
2:01:17 PM: FAILED to create exampleSite for hugo-now-ui
```

Can you please look into this issue and let me know?

Thanks

ref: https://github.com/gohugoio/hugoThemes/issues/531

**Comment by cboettig** [comment]
@onedrawingperday Thanks, looks like I didn't have the things properly set up for the baseurl for the example site. Should now be fixed in the demo that deploys from the `docs` dir on GitHub.

The netlify deploy looks related to the Hugo version though?  I've bumped the Hugo version as well in the `theme.toml` metadata.

**Comment by onedrawingperday** [comment]
@cboettig 

>The netlify deploy looks related to the Hugo version though? I've bumped the Hugo version as well in the `theme.toml` metadata.

Nope. The Hugo version in `theme.toml` is used so that a user knows which is the minimum Hugo version that a theme uses.

The Netlify deploy of the Hugo Themes website is triggered by its own [Build Script](https://github.com/gohugoio/hugoThemes/blob/master/buildThemeSite.sh) and it always uses the latest Hugo.

---

Regarding the reason I opened this issue please have a look at the recently updated [README](https://github.com/gohugoio/hugoThemes#resources) of the Hugo Themes repository. I quote below:

>If your theme makes use of the Hugo Pipes methods toCSS and / or PostCSS, you need to take additional steps to make your theme compatible with the basic version of Hugo:
>
> - From the root of a Hugo project that uses your theme execute the command hugo server -this will generate the /resources/ folder under the project root-.
> - Or if you prefer to build the project simply run the command hugo -this will generate the resources under public/resources-.
> - Copy the generated resources folder and commit it directly under the root of your theme's repository.

You need to do the above for the theme demo to generate again on the Themes website.

---
>Thanks, looks like I didn't have the things properly set up for the baseurl for the example site. Should now be fixed in the demo that deploys from the docs dir on GitHub.

Actually if you are referring to the latest changes in commit https://github.com/cboettig/hugo-now-ui/commit/887816d11e63f9115d30e6420558c433bee25f21 it actually causes problems.

Here is a screenshot of the theme demo when I test it with the Hugo Themes Build Script

![screenshot_2019-01-06_19-59-55](https://user-images.githubusercontent.com/7918298/50739835-1e50a100-11ee-11e9-808e-c9984d6ffea3.jpg)

Again please have a look at the recently updated [Common Permalink Issues](https://github.com/gohugoio/hugoThemes#common-permalink-issues) of the Hugo Themes README.

I also noticed that in this commit you have added this directory in the img `src` attribute `/hugo-now-ui/`
This directory is not needed and it actually breaks your images because it is not present under the `/static/` folder of the `exampleSite`.

The problem you had with those images not showing in the demo is due to the following (quote from the Themes README):

>Make sure not to use a forward slash `/` in the beginning of a URL, because it will point to the host root and Hugo will not generate the correct URL for the demo's assets.

**Comment by cboettig** [comment]
@onedrawingperday Thanks for your help and apologies for my confusion.  

- I've just added `resources` dir to the repository root, as requested.  Please let me know if I've missed anything in doing so.  

Regarding 

> I also noticed that in this commit you have added this directory in the img src attribute /hugo-now-ui/
This directory is not needed and it actually breaks your images because it is not present under the /static/ folder of the exampleSite.
> The problem you had with those images not showing in the demo is due to the following (quote from the Themes README):

Thanks for looking into this closely, I appreciate that effort.  Unfortunately, I'm still confused here.  Writing those attributes without the first forward slash, e.g.  as `src="img/ryan.jpg"` means that the path renders as something like `http://127.0.0.1:4321/hugo-now-ui/landing/img/ryan.jpg` instead of `http://127.0.0.1:4321/hugo-now-ui/img/ryan.jpg`, and thus none of the resources are resolved.  Getting image resources to resolve correctly in both local preview and in the GitHub preview from the `docs` folder of master branch, and on the themes website continues to stump me.  sorry if I'm missing something obvious.

**Comment by onedrawingperday** [comment]
@cboettig 
You could assign [Enviroment Variables](https://gohugo.io/getting-started/configuration/#configure-with-environment-variables) for local testing and then in your theme's templates you can use the [`getenv`](https://gohugo.io/functions/getenv/#readout) function to have these assets served as you need them in your local network i.e. `http://127.0.0.1:4321/hugo-now-ui/landing/img/ryan.jpg` but for the actual theme as I said above the addition of `/hugo-now-ui/` in the URLs is problematic both for the Themes site demo and the end user because this drectory is not present and these images will always throw a 404.

**Comment by cboettig** [comment]
@onedrawingperday thanks, but as you know, these are URLs to assets specific to the content, and have no place in a template file.  (The inability to use variables in content, rather than just in templates, has been the one thing about moving from Jekyll to Hugo that continues to frustrate me; though in most other ways I vastly prefer the Hugo patterns).  

Short of moving all content into templates and having empty place-holder content entries with only yaml headers, I don't see a way around this.  And providing an example site where content all opaquely comes in from a template would rather seem to defeat the purpose of creating an example site for new users getting started.  

I don't think that having a site that can render locally with `hugo`, display on GitHub pages, and still be compatible with the Hugo Themes page should be a particularly whacky or unusual idea, but I really don't see a way to do this.  How is this usually handled?  

I can switch to `src="/img/..."` and things will at least work locally, but I really don't understand doing `src="img/"` *without* the leading slash.  I don't have a separate `img` directory for each page.  I don't want to get URL references that are: `http://127.0.0.1:4321/hugo-now-ui/landing/img/ryan.jpg` because `landing/img` doesn't exist, this should just be `/img` which is why i am using the leading slash.  I just don't understand how you add images in content without a leading slash and get them to resolve correctly.  What am I missing??

**Comment by onedrawingperday** [comment]
>(The inability to use variables in content, rather than just in templates, has been the one thing about moving from Jekyll to Hugo that continues to frustrate me; though in most other ways I vastly prefer the Hugo patterns).

I think that you can do the above in a way since Hugo 0.52. See: https://gohugo.io//templates/shortcode-templates/#inline-shortcodes

> I just don't understand how you add images in content without a leading slash and get them to resolve correctly. What am I missing??

The leading slash will point to the host root. The theme demo on the Hugo website is published in a subdirectory and in this case Hugo will not serve the correct URL.

>I don't think that having a site that can render locally with hugo, display on GitHub pages, and still be compatible with the Hugo Themes page should be a particularly whacky or unusual idea, but I really don't see a way to do this. How is this usually handled?

We recently had a long discussion investigating the behavior of inline styles in Theme Demos over here: https://github.com/gohugoio/hugo/issues/5488

Also note that the Hugo Themes Build Script uses [`canonifyURLs`](https://gohugo.io/getting-started/configuration/#all-configuration-settings)

I suggest that you try out the new Inline Shortcodes feature that was introduced in 0.52 and see if that fits your requirement, if not I suggest that you open a topic in the Hugo Forum -if you want- so that others can describe their workflows.

---

Anyway this issue is now resolved since you committed the new Resources as I originally asked. I'll keep it open for now but please note that currently as I am in the middle of https://github.com/gohugoio/hugoThemes/issues/531 and https://github.com/gohugoio/hugoThemes/issues/532 I already have quite a lot of issues open in various theme repos to keep track of and at some point I will close this issue because -as I said above- it has been resolved.

The demo will be generated again the next time that themes are updated in the Hugo repository (usually happens about once a week).

Thanks.

**Comment by cboettig** [comment]
@onedrawingperday thanks for your help, your patience, and your excellent work!  :100:.  

I believe I've also now resolved all the image rendering issues in each context.  

I apologize for taking so much of your time!
