### ISSUE TITLE
How would I change the main page?

### ISSUE THREAD

**Issue by AdrienKG** [cboettig/hugo-now-ui#28]
I'd like to change the main page to load a landing page. Currently it seems like the main page uses the list.html template and loads cards for all html/md files in the content/ folder.

Is there a way to change this?

**Comment by cboettig** [comment]
Recall that Hugo uses a look-up order to determine which layout is applied  to any page, including the home page: https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-home-page  As you can see in the look-up order rules, it uses `layouts/_default/list.html` because that's the first thing in the look-up order that exists.

Simply add a `layouts/index.html` or `layouts/home.html` to your project to define a different layout template as the homepage. 

HTH

**Comment by AdrienKG** [comment]
Great thanks! I'll read up on that.
