### ISSUE TITLE
proposition of url

### ISSUE THREAD

**Issue by JOduMonT** [cboettig/hugo-now-ui#4]
Hi Carl;

I really like your portage of this theme on hugo; great work 👍 

I know you probably use Hugo to publish this demo but you don't publish the source so I need to ask you to do the change instead of just a PR

so in the [index page](https://github.com/cboettig/hugo-now-ui/blob/master/docs/index.html#L1073)  
would be not rather than sending the link to the [original link](http://demos.creative-tim.com/now-ui-kit/nucleo-icons.html) instead of a dead end ?

**Comment by cboettig** [comment]
Hi @jodumont ,

Thanks for the kind words and the previous PR.

The index page is lifted directly from the original Creative Tim theme source, so you are indeed looking at the source code.  (Since it's just an example page I didn't bother coding the body into hugo templating,  and thus didn't re-map the relative URLs  that appear there, so some links are broken: the icons, also links to the example pages in the /examples section).  

A PR against the file you link would be welcome; feel free to just hard-code functional URLs into that file.  You should be able to simply build the `exampleSite` with hugo and it will update the `/docs` directory where the rendered version of http://cboettig.github.io/hugo-now-ui lives (see the `config.toml` in `exampleSite`.

**Comment by cboettig** [comment]
these links should all be fixed now in the demo.
